insert into MEMBER(MEMBER_ID, MEMBER_NAME, MEMBERSHIP_START_DATE, MEMBERSHIP_STATUS) values(1, 'Member1', '2020-12-03', true);
insert into MEMBER(MEMBER_ID, MEMBER_NAME, MEMBERSHIP_START_DATE, MEMBERSHIP_STATUS) values(2, 'Member2', '2020-12-23', true);
insert into MEMBER(MEMBER_ID, MEMBER_NAME, MEMBERSHIP_START_DATE, MEMBERSHIP_STATUS) values(3, 'Member3', '2020-12-15', true);
insert into MEMBER(MEMBER_ID, MEMBER_NAME, MEMBERSHIP_START_DATE, MEMBERSHIP_STATUS) values(4, 'Member4', '2020-12-11', true);
insert into MEMBER(MEMBER_ID, MEMBER_NAME, MEMBERSHIP_START_DATE, MEMBERSHIP_STATUS) values(5, 'Member5', '2020-12-13', true);