insert into BOOK(BOOK_ID, BOOK_NAME, AUTHOR_NAME, AVAILABLE_COPIES, TOTAL_COPIES) values(1, 'Book1', 'Author1', 5, 10);
insert into BOOK(BOOK_ID, BOOK_NAME, AUTHOR_NAME, AVAILABLE_COPIES, TOTAL_COPIES) values(2, 'Book2', 'Author2', 0, 10);
insert into BOOK(BOOK_ID, BOOK_NAME, AUTHOR_NAME, AVAILABLE_COPIES, TOTAL_COPIES) values(3, 'Book3', 'Author3', 10, 10);
insert into BOOK(BOOK_ID, BOOK_NAME, AUTHOR_NAME, AVAILABLE_COPIES, TOTAL_COPIES) values(4, 'Book4', 'Author1', 3, 10);
insert into BOOK(BOOK_ID, BOOK_NAME, AUTHOR_NAME, AVAILABLE_COPIES, TOTAL_COPIES) values(5, 'Book5', 'Author3', 5, 10);